server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: veriq-backend
  profiles:
    default: dev
  flyway:
    enabled: true
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
