ALTER TABLE organization ADD COLUMN IF NOT EXISTS organization_type VARCHAR(50) NOT NULL DEFAULT 'Enterprise';
ALTER TABLE organization ADD COLUMN IF NOT EXISTS contact_person VARCHAR(100) NOT NULL DEFAULT 'Primary Contact';
ALTER TABLE organization ADD COLUMN IF NOT EXISTS designation VARCHAR(100);
ALTER TABLE organization ADD COLUMN IF NOT EXISTS contact_mobile VARCHAR(30) NOT NULL DEFAULT 'N/A';
ALTER TABLE organization ADD COLUMN IF NOT EXISTS address_line1 VARCHAR(255);
ALTER TABLE organization ADD COLUMN IF NOT EXISTS address_line2 VARCHAR(255);
ALTER TABLE organization ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE organization ADD COLUMN IF NOT EXISTS state VARCHAR(100);
ALTER TABLE organization ADD COLUMN IF NOT EXISTS country VARCHAR(100);
ALTER TABLE organization ADD COLUMN IF NOT EXISTS pin_code VARCHAR(20);
ALTER TABLE organization ADD COLUMN IF NOT EXISTS project_count INT NOT NULL DEFAULT 0;

ALTER TABLE organization DROP COLUMN IF EXISTS industry;
ALTER TABLE organization DROP COLUMN IF EXISTS tier;
