ALTER TABLE asset ADD COLUMN IF NOT EXISTS start_chainage NUMERIC(12, 3);
ALTER TABLE asset ADD COLUMN IF NOT EXISTS end_chainage NUMERIC(12, 3);
ALTER TABLE asset ADD COLUMN IF NOT EXISTS total_length NUMERIC(12, 3);
